session_name: dev
windows:
  - window_name: local
    layout: tiled
    panes:
      - cd ~/home-lab/
  - window_name: notes
    layout: tiled
    panes:
      - cd ~/brain-child/fr3d/
      - cd ~/notes/
