# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory $git_branch $git_commit $git_status 
$aws $azure $gcloud $terraform $kubernetes $python 
$character
"""




[directory]
read_only = " "
home_symbol = "~"
truncation_length = 3
truncate_to_repo = true # truncates directory to root folder if in github repo
style = " bold blue"


[character]
success_symbol = " [→](bold white)"
error_symbol = " [×](bold red)"

#right_format = '$aws $terraform'

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 5

# Disable the blank line at the start of the prompt
add_newline = true

[line_break]
disabled = false


[custom.tztime]
command = 'date +"%a %b %d %Y %T"'
when = "true"
format = ' [\[🕙 $symbol($output)\]]($style)'
style= "italic white"
disabled= true

[python]
symbol = "🐍 "
version_format = "v${raw}"
pyenv_version_name = true

[aws]
format = '[ ($profile )(\($region\) )]($style)'
style = "#bf5700"
[aws.region_aliases]
us-east-1 = "ue-1"
[aws.profile_aliases]
Admin = 'Administrator'
account-admin = 'acct-adm'

[gcloud]
disabled = false
format = ' IAM: [$symbol$account(@$domain)(\($project\))]($style) '
style = "#FEFB61"
symbol = ""

[git_branch]
format = " [$symbol $branch]($style) "
symbol = "🪵 "
style = "bold yellow"

[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨 ×${count}"
behind = "🐢 ×${count}"
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
untracked = "🛤️  ×${count}"
stashed = "📦 "
modified = "📜 ×${count} "
staged = "🗃️  ×${count} "
renamed = "📛 ×${count}"
deleted = "🗑️  ×${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[git_commit]
commit_hash_length = 5
style = "bold yellow"

[pulumi]
symbol = "⚙️ "
format = " [$symbol $stack]($style)"
style = "bright-purple"
disabled = false

[terraform]
format = " [🛠️ $version]($style) "

[kubernetes]
format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed blue) '
disabled = false

[azure]
disabled = false
format = "on [$symbol($subscription)]($style) "
symbol = "ﴃ "
style = "blue bold"
