# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.cursor]
text = "#1d1f21"
cursor = "#c5c8c6"

[colors.selection]
text = "#c5c8c6"
background = "#445060"

[colors.normal]
white = "#c5c8c6"
red = "#cc6666"
yellow = "#f0c674"
cyan = "#8abeb7"
magenta = "#b294bb"
green = "#b5bd68"
black = "#1d1f21"
blue = "#81a2be"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.bright]
white = "#eaeaea"
red = "#d54e53"
yellow = "#e7c547"
cyan = "#70c0b1"
magenta = "#c397d8"
green = "#b9ca4a"
black = "#373b41"
blue = "#7aa6da"
