# Colors (Tomorrow Night Bright)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#00FF00'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#00FF00'
green   = '#00FF00'
yellow  = '#00FF00'
blue    = '#00FF00'
magenta = '#00FF00'
cyan    = '#00FF00'
white   = '#00FF00'

# Bright colors
[colors.bright]
black   = '#00FF00'
red     = '#00FF00'
green   = '#00FF00'
yellow  = '#00FF00'
blue    = '#00FF00'
magenta = '#00FF00'
cyan    = '#00FF00'
white   = '#00FF00'
