theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true
shell = ["bash", "-c" ]
auto-save = true
auto-format = true

[editor.statusline]
left = ["mode", "spinner","version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
snippets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
a = "move_char_left" # Maps the 'a' key to the move_char_left command
w = "move_line_up" # Maps the 'w' key move_line_up
"C-S-esc" = "extend_line" # Maps Ctrl-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal."t"]
i=":run-shell-command terraform init -backend-config='remote.tfbackend' -upgrade"
p=":run-shell-command terraform plan -out='plan'"
a=":run-shell-command terraform apply -auto-approve 'plan'"
